management:
  endpoints:
    web:
      exposure:
        include: [ "health" ]
      base-path: /
      path-mapping:
        health: healthcheck
---
server:
  port: 8080
  servlet:
    context-path: /quote-orchestrator
spring:
  config:
    activate:
      on-profile: quote-orchestrator
  datasource:
    url: null
application:
  account-store-uri: http://localhost:8081/account-store
---
server:
  port: 8081
  servlet:
    context-path: /account-store
spring:
  config:
    activate:
      on-profile: account-store
  datasource:
    url: jdbc:h2:mem:db
